{"name": "test_userligin", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../config/data.yaml'", "trace": "self = <testcases.test_login.Test_Login object at 0x00000286121B07C8>\n\n    def setup(self):\n        self.app = App()\n>       self.main = self.app.start().goto_main()\n\ntestcases\\test_login.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page.app.App object at 0x00000286121B0A48>\n\n    def start(self):\n        #如果driver=None，则说明是首次打开app\n        if self._driver == None:\n            logging.info('driver=None，读取yaml配置文件')\n>           with open('../config/data.yaml','r',encoding='utf-8') as file:\nE           FileNotFoundError: [Errno 2] No such file or directory: '../config/data.yaml'\n\npage\\app.py:17: FileNotFoundError"}, "start": 1620122274917, "stop": 1620122274917, "uuid": "6c96adc6-bfde-4000-8b21-d1817f19f5e0", "historyId": "38b30ae280a19d01e564ed62aa924ef1", "testCaseId": "83451324d1c85e0d701ce7a820c8b3fb", "fullName": "testcases.test_login.Test_Login#test_userligin", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "hz-zb-zhang"}, {"name": "thread", "value": "11732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}